<a href="https://colab.research.google.com/github/PrasopchokGot/MathHobby/blob/main/Least_square_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Least square solution

$$ \begin{align}
(A^TA)x_{ls} &= A^Ty \\
x_{ls} &= (A^TA)^{-1}A^Ty
\end{align}$$
$$ $$

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 1], [0, 1], [0, 0]])
y = np.array([1, 0, 1])

In [ ]:
x_ls1 = (np.linalg.inv((A.transpose()@A)))@A.transpose()@y.transpose()
x_ls1

array([1., 0.])

In [ ]:
x_ls2 = np.linalg.lstsq(A, y, rcond=None)[0]
x_ls2

array([ 1.00000000e+00, -1.20292797e-16])

# Least square solution by QR factorization 

$$ \begin{align}
A = QR ⟹ x_{ls} &= (A^TA)^{-1}A^Ty=(R^{-1}Q^{-1}QR)R^TQ^Ty=R^TQ^Ty \\
x_{ls} &=R^TQ^Ty
\end{align}$$
$$ $$

In [ ]:
Q, R = np.linalg.qr(A)

In [ ]:
Q

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
R

array([[1., 1.],
       [0., 1.]])

In [ ]:
x_ls3 = np.linalg.inv(R)@Q.transpose()@y.transpose()
x_ls3

array([1., 0.])